### PR TITLE
Computing motion vertices from velocities and accelerations

### PR DESCRIPTION
**Pull request by dedoardo**
**Overview**
Computing motion blur geometry from velocity and acceleration attributes if no positions have been authored.
It includes [this bugfix](https://github.com/tangent-opensource/cycles/pull/5) from upstream.

**Changes**
- Added new attributes for velocity, acceleration and angular velocity
- Compute vertex positions during the geometry preprocessing stage using all the available attributes

**Comments**
The angular velocity is used to rotate vertices around the origin, should that be the center of mass? Having a real use case of angular velocity to check if it behaves as expected would be useful.

[Here](https://github.com/tangent-opensource/cycles/files/6031584/motion_blur.zip) is an example fluid simulation. 

See the related [HdCycles PR](https://github.com/tangent-opensource/hdcycles/pull/77)

### CODE REVIEW

**Comment by skwerner** [comment]
Were you able to verify if angular acceleration matches Karma's results? My understanding of Houdini's documentation is that XYZ are to be understood as an axis and that W is the rotation around that axis. I would not expect this to be Euler angles as those would depend on a defined rotation order.

**Comment by skwerner** [comment]
We should also be following Blender's Style Guide for our Cycles code:
https://wiki.blender.org/wiki/Style_Guide/C_Cpp

For example, number literals should read `1.0f` instead of `1.f`, comments to be written in `/* C style */` instead of `// C++ style`.

**Comment by dedoardo** [comment]
Addressed the coding style. 

Regarding the angular velocity attribute, the [Houdini docs ](https://www.sidefx.com/docs/houdini/render/blur.html#velocity) report it being the rotation speed in radians per second around X, Y, Z. [This blog post](https://www.sidefx.com/forum/topic/43027/?page=1#post-193324) also mentions that the rotation could be around the center of mass. It's not an official source, but maybe the geometry should be translated before rotation. 
I will check that the calculations match karma.

Doing some more investigation, acceleration and angular velocity seem to be designed more for particle systems. The existence of accelerations for fluid simulations doesn't seem far fetched, but maybe there is no use case for it in a `Mesh` and should live somewhere else. I am still trying to wrap my head around this, will report with more information.

**Comment by dedoardo** [comment]
Angular velocities for meshes do not make a lot of sense, I thus removed them from this PR. It's something more specific to instancing and should probably be handled in a separate PR.

**Pull request merged**
