### PR TITLE
adding rtc namesapce

### PR DESCRIPTION
**Pull request by bareya**
Adding Embree `RTC_NAMESPACE` namespace

### CODE REVIEW

**Comment by skwerner** [comment]
This doesn't compile here - `Rez-build` with variants 0, 1, 2 all return errors because `RTC_NAMESPACE` is undefined.

I suggest that instead of explicitly using `RTC_NAMESPACE` in front of every call, we use a single `RTC_NAMESPACE_OPEN` in the beginning of files using Embree instead. Since all Embree calls are prefixed with `rtc`, I think we can live with going against C++ best practices here.

**Review by skwerner — CHANGES_REQUESTED** [review]
Why was bvh_embree.cpp not changed?

**Comment by bareya** [comment]
I am going to check why it's not defined, this https://github.com/embree/embree/blame/master/kernels/rtcore_config.h.in#L21 has been added 2ys ago.

**Comment by skwerner** [comment]
It's only defined when `EMBREE_API_NAMESPACE` is defined. The `#else` case does not define `RTC_NAMESPACE`, that's when you get the compile error. `RTC_NAMESPACE_USE` is defined in both cases and should thus be safe to use.

**Comment by bareya** [comment]
@skwerner ready to be reviewed

**Review by skwerner — APPROVED** [review]

**Pull request merged**
